DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES (
    GENRE_ID BIGINT auto_increment PRIMARY KEY,
    GENRE_NAME VARCHAR(255)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS (
    AUTHOR_ID BIGINT auto_increment PRIMARY KEY,
    AUTHOR_NAME VARCHAR(255)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
    BOOK_ID BIGINT auto_increment PRIMARY KEY,
    BOOK_NAME VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID BIGINT,
    foreign key (AUTHOR_ID) references AUTHORS(AUTHOR_ID),
    foreign key (GENRE_ID) references GENRES(GENRE_ID)
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS (
    COMMENT_ID BIGINT auto_increment PRIMARY KEY,
    COMMENT_TEXT VARCHAR(255),
    BOOK_ID BIGINT,
    foreign key (BOOK_ID) references BOOKS(BOOK_ID)
);