INSERT INTO GENRES (GENRE_ID, GENRE_NAME)
VALUES
(1, 'Детектив');

INSERT INTO AUTHORS (AUTHOR_ID, AUTHOR_NAME)
VALUES
(1, 'Агата Кристи');

INSERT INTO BOOKS (BOOK_ID, BOOK_NAME, AUTHOR_ID, GENRE_ID)
VALUES
(1, 'Пуаро', 1, 1);

