spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      database: book-db
      authentication-database: none
      port: 27017
      host: localhost
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - com.polozov.bookproject.changelog
